<?php

namespace AppBundle\Repository;

/**
 * OrderSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
