admin_blog_index:
    path:     /
    defaults: { _controller: "AppBundle:Blog:index" }
    methods:  GET

admin_blog_show:
    path:     /show/{id}
    defaults: { _controller: "AppBundle:Blog:show" }
    methods:  GET

admin_blog_new:
    path:     /new
    defaults: { _controller: "AppBundle:Blog:new" }
    methods:  [GET, POST]

admin_blog_edit:
    path:     /edit/{id}
    defaults: { _controller: "AppBundle:Blog:edit" }
    methods:  [GET, POST]

admin_blog_delete:
    path:     /delete/{id}
    defaults: { _controller: "AppBundle:Blog:delete" }
    methods:  DELETE
