admin_klijenti_index:
    path:     /
    defaults: { _controller: "AppBundle:Clients:index" }
    methods:  GET

admin_klijenti_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Clients:show" }
    methods:  GET

admin_klijenti_new:
    path:     /new
    defaults: { _controller: "AppBundle:Clients:new" }
    methods:  [GET, POST]

admin_klijenti_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Clients:edit" }
    methods:  [GET, POST]

admin_klijenti_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Clients:delete" }
    methods:  DELETE
