AppBundle\Entity\OrderSite:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OrderSiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        theme:
            type: string
            length: 255
        domen:
            type: string
            length: 255
        host:
            type: integer
        socialn:
            type: integer
        material:
            type: integer
        description:
            type: string
            length: '455'
        name:
            type: string
            length: '85'
        email:
            type: string
            length: '65'
        phone:
            type: string
            length: '20'
        isRead:
            type: boolean
            column: is_read
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
